# Generated by Django 3.2.5 on 2022-04-19 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import reporter.frame.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_sku', models.CharField(max_length=30)),
                ('thumb', models.ImageField(default='thumb.jpg', upload_to='static/media/frame_thumb')),
                ('is_text', models.BooleanField(default=0)),
                ('text_pos', django_enumfield.db.fields.EnumField(default=1, enum=reporter.frame.models.TextPos)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'frames',
            },
        ),
        migrations.CreateModel(
            name='FrameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('thumb', models.ImageField(default='thumb.jpg', upload_to='static/media/cat_thumb')),
                ('active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'frame_categories',
            },
        ),
        migrations.CreateModel(
            name='FrameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', django_enumfield.db.fields.EnumField(default=0, enum=reporter.frame.models.FrameAspectRatio)),
                ('frame_media', models.FileField(default='frame.gif', upload_to='static/media/frames', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'gif', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_file', to='frame.frame')),
            ],
            options={
                'db_table': 'frame_files',
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame', to='frame.framecategory'),
        ),
    ]
